export const moviesList = [
  {
    name: "33 слова о дизайне",
    image: "обложка фильма",
    duration: "1ч 47м",
    owner: true,
  },
  {
    name: "Киноальманах «100 лет дизайна»",
    image: "обложка фильма",
    duration: "1ч 3м",
    owner: false,
  },
  {
    name: "В погоне за Бенкси",
    image: "обложка фильма",
    duration: "1ч 42м",
    owner: false,
  },
  {
    name: "Баския: Взрыв реальности",
    image: "обложка фильма",
    duration: "1ч 21м",
    owner: false,
  },
  {
    name: "Бег это свобода",
    image: "обложка фильма",
    duration: "1ч 44м",
    owner: false,
  },
  {
    name: "Книготорговцы",
    image: "обложка фильма",
    duration: "1ч 37м",
    owner: true,
  },
  {
    name: "Когда я думаю о Германии ночью",
    image: "обложка фильма",
    duration: "1ч 56м",
    owner: false,
  },
  {
    name: "Gimme Danger: История Игги и The Stooge...",
    image: "обложка фильма",
    duration: "1ч 59м",
    owner: false,
  },
  {
    name: "Дженис: Маленькая девочка грустит",
    image: "обложка фильма",
    duration: "1ч 42м",
    owner: true,
  },
  {
    name: "Соберись перед прыжком",
    image: "обложка фильма",
    duration: "1ч 10м",
    owner: true,
  },
  {
    name: "Пи Джей Харви: A dog called money",
    image: "обложка фильма",
    duration: "1ч 4м",
    owner: false,
  },
  {
    name: "По волнам: Искусство звука в кино",
    image: "обложка фильма",
    duration: "1ч 7м",
    owner: false,
  },
  {
    name: "33 слова о дизайне",
    image: "обложка фильма",
    duration: "1ч 47м",
    owner: true,
  },
  {
    name: "Киноальманах «100 лет дизайна»",
    image: "обложка фильма",
    duration: "1ч 3м",
    owner: false,
  },
  {
    name: "В погоне за Бенкси",
    image: "обложка фильма",
    duration: "1ч 42м",
    owner: false,
  },
  {
    name: "Баския: Взрыв реальности",
    image: "обложка фильма",
    duration: "1ч 21м",
    owner: false,
  },
  {
    name: "Бег это свобода",
    image: "обложка фильма",
    duration: "1ч 44м",
    owner: false,
  },
  {
    name: "Книготорговцы",
    image: "обложка фильма",
    duration: "1ч 37м",
    owner: true,
  },
  {
    name: "Когда я думаю о Германии ночью",
    image: "обложка фильма",
    duration: "1ч 56м",
    owner: false,
  },
  {
    name: "Gimme Danger: История Игги и The Stooge...",
    image: "обложка фильма",
    duration: "1ч 59м",
    owner: false,
  },
  {
    name: "Дженис: Маленькая девочка грустит",
    image: "обложка фильма",
    duration: "1ч 42м",
    owner: true,
  },
  {
    name: "Соберись перед прыжком",
    image: "обложка фильма",
    duration: "1ч 10м",
    owner: true,
  },
  {
    name: "Пи Джей Харви: A dog called money",
    image: "обложка фильма",
    duration: "1ч 4м",
    owner: false,
  },
  {
    name: "По волнам: Искусство звука в кино",
    image: "обложка фильма",
    duration: "1ч 7м",
    owner: false,
  },
];
