export const moviesList = [
  {
    nameRU: "33 слова о дизайне",
    trailerLink: "https://www.youtube.com/",
    duration: "1ч 47м",
    owner: true,
  },
  {
    nameRU: "Киноальманах «100 лет дизайна»",
    trailerLink: "https://www.youtube.com/",
    duration: "1ч 3м",
    owner: false,
  },
  {
    nameRU: "В погоне за Бенкси",
    trailerLink: "https://www.youtube.com/",
    duration: "1ч 42м",
    owner: false,
  },
  {
    nameRU: "Баския: Взрыв реальности",
    trailerLink: "https://www.youtube.com/",
    duration: "1ч 21м",
    owner: false,
  },
  {
    nameRU: "Бег это свобода",
    trailerLink: "https://www.youtube.com/",
    duration: "1ч 44м",
    owner: false,
  },
  {
    nameRU: "Книготорговцы",
    trailerLink: "https://www.youtube.com/",
    duration: "1ч 37м",
    owner: true,
  },
  {
    nameRU: "Когда я думаю о Германии ночью",
    trailerLink: "https://www.youtube.com/",
    duration: "1ч 56м",
    owner: false,
  },
  {
    nameRU: "Gimme Danger: История Игги и The Stooge...",
    trailerLink: "https://www.youtube.com/",
    duration: "1ч 59м",
    owner: false,
  },
  {
    nameRU: "Дженис: Маленькая девочка грустит",
    trailerLink: "https://www.youtube.com/",
    duration: "1ч 42м",
    owner: true,
  },
  {
    nameRU: "Соберись перед прыжком",
    trailerLink: "https://www.youtube.com/",
    duration: "1ч 10м",
    owner: false,
  },
  {
    nameRU: "Пи Джей Харви: A dog called money",
    trailerLink: "https://www.youtube.com/",
    duration: "1ч 4м",
    owner: false,
  },
  {
    nameRU: "По волнам: Искусство звука в кино",
    trailerLink: "https://www.youtube.com/",
    duration: "1ч 7м",
    owner: false,
  },
  {
    nameRU: "33 слова о дизайне",
    trailerLink: "https://www.youtube.com/",
    duration: "1ч 47м",
    owner: false,
  },
  {
    nameRU: "Киноальманах «100 лет дизайна»",
    trailerLink: "https://www.youtube.com/",
    duration: "1ч 3м",
    owner: false,
  },
  {
    nameRU: "В погоне за Бенкси",
    trailerLink: "https://www.youtube.com/",
    duration: "1ч 42м",
    owner: false,
  },
  {
    nameRU: "Баския: Взрыв реальности",
    trailerLink: "https://www.youtube.com/",
    duration: "1ч 21м",
    owner: false,
  },
  {
    nameRU: "Бег это свобода",
    trailerLink: "https://www.youtube.com/",
    duration: "1ч 44м",
    owner: false,
  },
  {
    nameRU: "Книготорговцы",
    trailerLink: "https://www.youtube.com/",
    duration: "1ч 37м",
    owner: false,
  },
  {
    nameRU: "Когда я думаю о Германии ночью",
    trailerLink: "https://www.youtube.com/",
    duration: "1ч 56м",
    owner: false,
  },
  {
    nameRU: "Gimme Danger: История Игги и The Stooge...",
    trailerLink: "https://www.youtube.com/",
    duration: "1ч 59м",
    owner: false,
  },
  {
    nameRU: "Дженис: Маленькая девочка грустит",
    trailerLink: "https://www.youtube.com/",
    duration: "1ч 42м",
    owner: false,
  },
  {
    nameRU: "Соберись перед прыжком",
    trailerLink: "https://www.youtube.com/",
    duration: "1ч 10м",
    owner: false,
  },
  {
    nameRU: "Пи Джей Харви: A dog called money",
    trailerLink: "https://www.youtube.com/",
    duration: "1ч 4м",
    owner: false,
  },
  {
    nameRU: "По волнам: Искусство звука в кино",
    trailerLink: "https://www.youtube.com/",
    duration: "1ч 7м",
    owner: false,
  },
];
